### ISSUE TITLE
iRail API

### ISSUE THREAD

**Issue by pietercolpaert** [public-transport/public-transport-apps-encryption#2]
iRail APIs are all served over HTTPS

https://api.irail.be

**Comment by derhuerst** [comment]
Thanks for the hint!

Are there any apps that use this API? With this list, we mainly intend to document if apps use HTTPS.

**Comment by pietercolpaert** [comment]
A lot! A small selection:
 * BeTrains: https://play.google.com/store/apps/details?id=tof.cv.mpp&hl=nl
 * Railer: http://www.railer.be/
 * iRail.be
 * HyperRail: https://play.google.com/store/apps/details?id=be.hyperrail.android&hl=nl
 * Next Train smart watch app: http://nexttrain.tjeerdytsma.nl/
 * BeRail Sailfish OS app: https://github.com/iRail/harbour-berail
 * FlatTurtle digital signage solutions: http://www.getflatturtle.com/
