### ISSUE TITLE
Wie am einfachsten beobachten?

### ISSUE THREAD

**Issue by Wikinaut** [public-transport/public-transport-apps-encryption#3]
Es gibt sicher viele Möglichkeiten, den Netzverkehr (ob http/s benutzt wird) zu beobachten; es wäre nett, wenn Du hier noch eine für die meisten "nachbaubare" Lösung aufführen könntest.

Also was wäre Deine empfohlene "Messanordnung"?

**Comment by derhuerst** [comment]
Ich bin mir nicht sicher, ob diese Lösungen für die meisten nachbaubar sind. Im wesentlichen kenne ich zwei:

- Ein Tool wie [mitmproxy](https://mitmproxy.org) verwenden und alle Requests dorthin umleiten. Funktioniert nicht mit allen Apps, aber mit den meisten.
- Mit einem Tool wie [Wireshark](https://www.wireshark.org) oder [CocoaPacketAnalyzer](http://www.tastycocoabytes.com/cpa/) den Netzwerkverkehr mithören. Man sieht nicht, ob der HSTS-Header über HTTPS verschickt wird, aber ob HTTPS verwendet wird.

**Comment by kiliankoe** [comment]
Nebst mitmproxy kann ich auch Charles empfehlen. Wüsste auch nicht womit das nicht funktionieren sollte, aber spätestens bei certificate pinning rennt man gegen eine Wand und benötigt erheblichen Mehraufwand um weiterzumachen. Möglich ist es aber dennoch 😊

**Comment by derhuerst** [comment]
a part of [@kiliankoe's talk](https://blog.kilian.io/reverse-engineering-ios/) is relevant as well
